# port of HTTP
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

proxy-groups:
  - name: all
    type: load-balance
    use:
      - local_merge
      - pool_ip1
      - pool_ip2
      - pool_ip3
      - pool_crazy
      - pool_link
    url: "http://www.gstatic.com/generate_204"
    interval: 300

proxy-providers:
  local_merge:
    type: file
    path: "./sub/sub_merge_yaml.yml"
    health-check: { enable: true, interval: 600, url: http://www.gstatic.com/generate_204 }
  pool_ip1:
    type: http
    url: "http://141.147.161.50:12580/clash/proxies"
    path: ./providers/pool_ip1.yml
    optional: true
    health-check: { enable: true, interval: 600, url: http://www.gstatic.com/generate_204 }
  pool_ip2:
    type: http
    url: "http://155.248.172.106:12580/clash/proxies"
    path: ./providers/pool_ip2.yml
    optional: true
    health-check: { enable: true, interval: 600, url: http://www.gstatic.com/generate_204 }
  pool_ip3:
    type: http
    url: "http://66.42.50.118:12580/clash/proxies"
    path: ./providers/pool_ip3.yml
    optional: true
    health-check: { enable: true, interval: 600, url: http://www.gstatic.com/generate_204 }
  pool_crazy:
    type: http
    url: "https://proxy.crazygeeky.com/clash/proxies"
    path: ./providers/pool_crazy.yml
    optional: true
    health-check: { enable: true, interval: 600, url: http://www.gstatic.com/generate_204 }
  pool_link:
    type: http
    url: "https://proxypool.link/clash/proxies"
    path: ./providers/pool_link.yml
    optional: true
    health-check: { enable: true, interval: 600, url: http://www.gstatic.com/generate_204 }

rules:
  - DOMAIN-SUFFIX,githubusercontent.com,DIRECT
  - DOMAIN-SUFFIX,github.com,DIRECT
  - MATCH,all